## Sample Organization kind (Cluster-scoped)
apiVersion: core.choreo.dev/v1
kind: Organization
metadata:
  name: acme
  annotations:
    core.choreo.dev/display-name: ACME Organization
    core.choreo.dev/description: Choreo Organization for ACME
  labels:
    core.choreo.dev/name: acme
spec: {}