apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: greeting-service
  namespace: default
spec:
  owner:
    projectName: default
  type: Service

---
apiVersion: openchoreo.dev/v1alpha1
kind: Build
metadata:
  name: greeting-service-build-01
  namespace: default
spec:
  owner:
    componentName: greeting-service
    projectName: default
  repository:
    appPath: /greeting-service-go
    revision:
      branch: main
    url: https://github.com/wso2/choreo-samples
  templateRef:
    name: docker
    parameters:
      - name: docker-context
        value: /greeting-service-go
      - name: dockerfile-path
        value: /greeting-service-go/Dockerfile

---
apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: greeting-service
spec:
  owner:
    componentName: greeting-service
    projectName: default
  containers:
    main:
      image: "test:latest"
      command:
        - ./go-greeter
      args:
        - --port
        - "9090"
  endpoints:
    rest-api:
      type: REST
      port: 9090
      schema:
        type: REST
        content: |
          openapi: 3.0.0
          info:
              title: Greeter API
              version: v1
          paths:
              /greet:
              get:
                  summary: Greet a user
                  responses:
                  '200':
                      description: A greeting message
                      content:
                      application/json:
                          schema:
                          type: object
                          properties:
                              message:
                              type: string
                              example: Hello, World!

---
apiVersion: openchoreo.dev/v1alpha1
kind: Service
metadata:
  name: greeting-service
spec:
  owner:
    componentName: greeting-service
    projectName: default
  workloadName: greeting-service
  className: default
  overrides: { }
  apis:
    greeter-api:
      type: REST
      className: default
      rest:
        backend:
          port: 9090
          basePath: /greeter
        exposeLevels: [ "Public" ]
