{{ if .Values.global.defaultResources.enabled }}
---
apiVersion: openchoreo.dev/v1alpha1
kind: APIClass
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "8"
  labels:
    {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
spec:
  restPolicy:
    defaults:
      rateLimit:
        requests: 5
        window: "1m"
      authentication:
        type: jwt
        jwt:
          jwks: "https://dev-tfsf6412a2bn011a.us.auth0.com/.well-known/jwks.json"
          issuer: "https://dev-tfsf6412a2bn011a.us.auth0.com/"
          audience: ["openchoreo:greeter:service"]
        oauth2:
          scopes: ["greet"]
          tokenUrl: "https://dev-tfsf6412a2bn011a.us.auth0.com/oauth/token"
      cors:
        allowOrigins: ["https://example.com", "https://app.example.com"]
        allowMethods: ["GET", "POST", "PUT", "DELETE"]
        allowHeaders: ["Content-Type", "Authorization"]
        exposeHeaders: ["X-Request-ID"]
        maxAge: 86400
      timeout: "30s"
      retries:
        attempts: 3
        backoff: "exponential"
        initialInterval: "1s"
        maxInterval: "10s"
      requestSizeLimit: "10MB"
      responseSizeLimit: "50MB"
      circuitBreaker:
        enabled: true
        maxConnections: 2
      monitoring:
        metrics:
          enabled: true
          detailedMetrics: true
        logging:
          enabled: true
          logLevel: "info"
          includeRequestBody: false
          includeResponseBody: false
    public:
      rateLimit:
        requests: 5
        window: "1h"
      security:
        requireTLS: true
        minTLSVersion: "1.3"
    organization:
      rateLimit:
        requests: 5000
        window: "1h"
{{ end }}
