{{- if .Values.fluentBit.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fluentBit.rbac.serviceAccountName }}
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
  labels:
    {{- include "openchoreo-build-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: fluent-bit
{{- end }}
