kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: choreo
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: /tmp/kind-shared
        containerPath: /mnt/shared
networking:
  disableDefaultCNI: true
