header:
  license:
    name: OpenChoreo
    content: |
      Copyright 2025 The OpenChoreo Authors
      SPDX-License-Identifier: Apache-2.0

  paths:
    - '**/*.go'

  paths-ignore:
    - 'internal/dataplane/kubernetes/argoproj.io/'
    - 'internal/dataplane/kubernetes/cilium.io/'
    - 'internal/dataplane/kubernetes/secretstorecsi/'

  comment: on-failure
  license-location-threshold: 80

  language:
    Go:
      extensions:
        - ".go"
      comment_style_id: DoubleSlash