apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "openchoreo-control-plane.fullname" . }}-{{ .Values.controllerManager.name }}
  labels:
  {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "openchoreo-control-plane.fullname" . }}-{{ .Values.controllerManager.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.controllerManager.name }}
  namespace: {{ .Release.Namespace }}
