apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controllerManager.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openchoreo-control-plane.componentLabels" (dict "context" . "component" .Values.controllerManager.name) | nindent 4 }}
