apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.controllerManager.name }}-selfsigned-issuer
  labels:
  {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
spec:
  selfSigned: {}
