apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.controllerManager.name }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "openchoreo-control-plane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: {{ .Values.controllerManager.name }}
    {{- include "openchoreo-control-plane.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}
