apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: productcatalog
spec:
  owner:
    projectName: gcp-microservice-demo
  type: Service

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: productcatalog
spec:
  owner:
    componentName: productcatalog
    projectName: gcp-microservice-demo
  containers:
    main:
      image: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice:v0.10.3
      env:
        - key: DISABLE_PROFILER
          value: "1"
        - key: PORT
          value: "3550"
  endpoints:
    grpc-endpoint:
      type: gRPC
      port: 3550
      schema:
        type: gRPC
        content: |
          service ProductCatalogService {
              rpc ListProducts(Empty) returns (ListProductsResponse) {}
              rpc GetProduct(GetProductRequest) returns (Product) {}
              rpc SearchProducts(SearchProductsRequest) returns (SearchProductsResponse) {}
          }

          message Product {
              string id = 1;
              string name = 2;
              string description = 3;
              string picture = 4;
              Money price_usd = 5;

              // Categories such as "clothing" or "kitchen" that can be used to look up
              // other related products.
              repeated string categories = 6;
          }

          message ListProductsResponse {
              repeated Product products = 1;
          }

          message GetProductRequest {
              string id = 1;
          }

          message SearchProductsRequest {
              string query = 1;
          }

          message SearchProductsResponse {
              repeated Product results = 1;
          }

---
apiVersion: openchoreo.dev/v1alpha1
kind: Service
metadata:
  name: productcatalog
spec:
  owner:
    componentName: productcatalog
    projectName: gcp-microservice-demo
  workloadName: productcatalog
  overrides: {}
