# permissions for end users to view endpointv2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openchoreo
    app.kubernetes.io/managed-by: kustomize
  name: endpointv2-viewer-role
rules:
- apiGroups:
  - openchoreo.dev
  resources:
  - endpointv2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openchoreo.dev
  resources:
  - endpointv2s/status
  verbs:
  - get
