# permissions for end users to view scheduledtaskreleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: choreo
    app.kubernetes.io/managed-by: kustomize
  name: scheduledtaskrelease-viewer-role
rules:
- apiGroups:
  - core.choreo.dev
  resources:
  - scheduledtaskreleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.choreo.dev
  resources:
  - scheduledtaskreleases/status
  verbs:
  - get
