# permissions for end users to view scheduledtasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openchoreo
    app.kubernetes.io/managed-by: kustomize
  name: scheduledtask-viewer-role
rules:
- apiGroups:
  - openchoreo.dev
  resources:
  - scheduledtasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openchoreo.dev
  resources:
  - scheduledtasks/status
  verbs:
  - get
