# permissions for end users to view scheduledtaskclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openchoreo
    app.kubernetes.io/managed-by: kustomize
  name: scheduledtaskclass-viewer-role
rules:
- apiGroups:
  - openchoreo.dev
  resources:
  - scheduledtaskclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openchoreo.dev
  resources:
  - scheduledtaskclasses/status
  verbs:
  - get
