apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: ad
spec:
  owner:
    projectName: gcp-microservice-demo
  type: Service

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: ad
spec:
  owner:
    componentName: ad
    projectName: gcp-microservice-demo
  containers:
    main:
      image: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice:v0.10.3
      env:
        - key: PORT
          value: "9555"
  endpoints:
    grpc-endpoint:
      type: gRPC
      port: 9555
      schema:
        type: gRPC
        content: |
          syntax = "proto3";

          package hipstershop;

          service AdService {
              rpc GetAds(AdRequest) returns (AdResponse) {}
          }

          message AdRequest {
              // List of important key words from the current page describing the context.
              repeated string context_keys = 1;
          }

          message AdResponse {
              repeated Ad ads = 1;
          }

          message Ad {
              // url to redirect to when an ad is clicked.
              string redirect_url = 1;

              // short advertisement text to display.
              string text = 2;
          }

---
apiVersion: openchoreo.dev/v1alpha1
kind: Service
metadata:
  name: ad
spec:
  owner:
    componentName: ad
    projectName: gcp-microservice-demo
  workloadName: ad
  overrides: {}
