{{- if .Values.fluentBit.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openchoreo-data-plane.name" . }}-fluent-bit-read
  labels:
    {{- include "openchoreo-data-plane.labels" . | nindent 4 }}
    app.kubernetes.io/component: fluent-bit
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
{{- end }}
