apiVersion: openchoreo.dev/v1alpha1
kind: ComponentV2
metadata:
  name: payment
spec:
  owner:
    projectName: gcp-microservice-demo
  type: Service

---

apiVersion: openchoreo.dev/v1alpha1
kind: Workload
metadata:
  name: payment
spec:
  owner:
    componentName: payment
    projectName: gcp-microservice-demo
  containers:
    main:
      image: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice:v0.10.3
      env:
        - key: DISABLE_PROFILER
          value: "1"
        - key: PORT
          value: "50051"
  endpoints:
    grpc-endpoint:
      type: gRPC
      port: 50051
      schema:
        type: gRPC
        content: |
          syntax = "proto3";

          package hipstershop;
          
          service PaymentService {
              rpc Charge(ChargeRequest) returns (ChargeResponse) {}
          }

          message CreditCardInfo {
              string credit_card_number = 1;
              int32 credit_card_cvv = 2;
              int32 credit_card_expiration_year = 3;
              int32 credit_card_expiration_month = 4;
          }

          message ChargeRequest {
              Money amount = 1;
              CreditCardInfo credit_card = 2;
          }

          message ChargeResponse {
              string transaction_id = 1;
          }

---
apiVersion: openchoreo.dev/v1alpha1
kind: Service
metadata:
  name: payment
spec:
  owner:
    componentName: payment
    projectName: gcp-microservice-demo    
  workloadName: payment
  overrides: {}
