apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:  {{ include "openchoreo-data-plane.fullname" . }}-csi-secrets-store-token-creator
subjects:
- kind: ServiceAccount
  name: default
  namespace:  {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name:  {{ include "openchoreo-data-plane.fullname" . }}-csi-secrets-store-token-creator
  apiGroup: rbac.authorization.k8s.io
