apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-wait-role
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "4"
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
