apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  hashicorp-vault-csi-secrets-store-token-creator
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
