## Append samples of your project ##
resources:
  - core_v1_organization.yaml
  - core_v1_build.yaml
  - core_v1_project.yaml
  - core_v1_deployableartifact.yaml
  - core_v1_organization.yaml
  - core_v1_project.yaml
  - core_v1_environment.yaml
  - core_v1_dataplane.yaml
  - core_v1_deploymentpipeline.yaml
  - core_v1_component.yaml
  - core_v1_deploymenttrack.yaml
  - core_v1_deployableartifact.yaml
  - core_v1_deployment.yaml
  - core_v1_endpoint.yaml
  - core_v1_configurationgroup.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
