## Append samples of your project ##
resources:
  - core_v1_organization.yaml
  - core_v1_build.yaml
  - core_v1_project.yaml
  - core_v1_deployableartifact.yaml
  - core_v1_organization.yaml
  - core_v1_project.yaml
  - core_v1_environment.yaml
  - core_v1_dataplane.yaml
  - core_v1_deploymentpipeline.yaml
  - core_v1_component.yaml
  - core_v1_deploymenttrack.yaml
  - core_v1_deployableartifact.yaml
  - core_v1_deployment.yaml
  - core_v1_endpoint.yaml
  - core_v1_configurationgroup.yaml
  - core_v1_componentv2.yaml
  - core_v1_workload.yaml
  - core_v1_endpointv2.yaml
  - core_v1_endpointclass.yaml
  - core_v1_gitcommitrequest.yaml
  - core_v1_api.yaml
  - core_v1_apiclass.yaml
  - core_v1_apibinding.yaml
  - core_v1_service.yaml
  - core_v1_serviceclass.yaml
  - core_v1_servicebinding.yaml
  - core_v1_webapplication.yaml
  - core_v1_webapplicationclass.yaml
  - core_v1_webapplicationbinding.yaml
  - core_v1_scheduledtask.yaml
  - core_v1_scheduledtaskclass.yaml
  - core_v1_scheduledtaskbinding.yaml
  - core_v1_release.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
