apiVersion: openchoreo.dev/v1alpha1
kind: Environment
metadata:
  annotations:
    openchoreo.dev/description: Staging
    openchoreo.dev/display-name: Staging
  labels:
    openchoreo.dev/name: staging
    openchoreo.dev/organization: default
  name: staging
  namespace: default
spec:
  dataPlaneRef: default
  gateway:
    dnsPrefix: staging
    security:
      remoteJwks:
        uri: ""