apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "choreo-control-plane.fullname" . }}-endpoint-admin-role
  labels:
  {{- include "choreo-control-plane.labels" . | nindent 4 }}
rules:
- apiGroups:
  - core.choreo.dev
  resources:
  - endpoints
  verbs:
  - '*'
- apiGroups:
  - core.choreo.dev
  resources:
  - endpoints/status
  verbs:
  - get
