apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workflow-cluster-role
subjects:
  - kind: ServiceAccount
    name: argo-workflow-sa
    namespace: choreo-ci-default-org
