# Customizing OpenSearch configurations
opensearch:
  image:
    repository: opensearchproject/opensearch
    tag: "2.11.0"
    pullPolicy: IfNotPresent
  
  service:
    type: NodePort
    httpPort: 9200
    transportPort: 9300
    nameSuffix: "opensearch"
    # NodePort configuration for cross-cluster access
    nodePort: 30920  # Fixed port for external access from other clusters
  
  config:
    clusterName: opensearch-cluster
    discoveryType: single-node
    javaOpts: "-Xms512m -Xmx512m"
    memoryLock: false
    disableSecurity: true
  
  authentication:
    basicauth:
      username: admin
      password: admin
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 5Gi
  
  replicas: 1

# Customizing OpenSearch Dashboards configurations
opensearchDashboard:
  image:
    repository: opensearchproject/opensearch-dashboards
    tag: "2.11.0"
    pullPolicy: IfNotPresent
  
  service:
    type: NodePort
    port: 5601
    nameSuffix: "opensearch-dashboard"
  
  config:
    disableSecurity: true
  
  replicas: 1

# Choreo Observer Service Configuration
observer:
  replicas: 1
  
  image:
    repository: ghcr.io/openchoreo/observer
    tag: latest-dev
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8080
  
  opensearch:
    # References the OpenSearch configuration above
    # address: constructed in observer-deployment.yaml template
    username: "{{ .Values.opensearch.authentication.basicauth.username }}"
    password: "{{ .Values.opensearch.authentication.basicauth.password }}"
  
  logLevel: info
  
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
