# Global configuration
global:
  # Common labels applied to all resources
  commonLabels: {}
  # Default build plane resources and configuration
  defaultResources:
    enabled: true
    # Container registry endpoint for pushing images
    registryEndpoint: "registry.openchoreo-data-plane.svc.cluster.local:5000"

# customizing the argo workflows configurations
argo-workflows:
  fullnameOverride: argo
  controller:
    # -- Resource limits and requests for the argo workflows controller
    resources:
      limits:
        memory: 64Mi
        cpu: 50m
      requests:
        memory: 32Mi
        cpu: 25m
  server:
    enabled: false
  crds:
    keep: false
  workflow:
    serviceAccount:
      create: true
  workflowNamespaces:
    - argo-build
