{{ if .Values.registry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: {{ .Values.registry.service.nodePort }}
  selector:
    app: registry
{{end}}
