{{- if .Values.logger.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: choreo-logger
  namespace: {{ .Release.Namespace }}
  labels:
    app: choreo-logger
    app.kubernetes.io/name: choreo-logger
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: logging
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "16"
spec:
  type: {{ if .Values.logger.service }}{{ .Values.logger.service.type | default "ClusterIP" }}{{ else }}ClusterIP{{ end }}
  ports:
  - port: {{ if .Values.logger.service }}{{ .Values.logger.service.port | default 8080 }}{{ else }}8080{{ end }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: choreo-logger
{{- end }}