apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredns-configmap-role
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "update", "patch"]
    resourceNames: ["coredns"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
