name: License Header Check

on:
  push:
  pull_request:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: ./.github/actions/setup-go

      - name: Install license-eye
        run: |
          go install github.com/apache/skywalking-eyes/cmd/license-eye@latest
          sed -i "s/Copyright [0-9]\{4\}/Copyright $(date +%Y)/" .licenserc.yaml
          cat .licenserc.yaml

      - name: Run license header check
        run: |
          echo "Running license header check..."
          license-eye header check || {
            echo "❌ License header check failed."
            echo ""
            echo "Please add the following header to the top of each Go file:"
            echo ""
            echo "// Copyright $(date +%Y) The OpenChoreo Authors"
            echo "// SPDX-License-Identifier: Apache-2.0"
            echo ""
            echo "Run \`license-eye header fix\` locally to fix."
            exit 1
          }
