name: License Header Check

on:
  push:
  pull_request:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: ./.github/actions/setup-go

      - name: Install license-eye
        run: |
          make install-license-eye
          make update-license-year
          cat .licenserc.yaml

      - name: Run license header check
        run: |
          echo "Running license header check..."
          license-eye header check || {
            echo "/n"
            echo "❌ License header check failed."
            echo "/n"
            echo "Please add the following header to the top of each Go file:"
            echo "/n"
            echo "// Copyright $(date +%Y) The OpenChoreo Authors"
            echo "// SPDX-License-Identifier: Apache-2.0"
            echo "/n"
            echo "Run \`make license-fix\` locally to fix."
            exit 1
          }
