name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: false
        default: ''
  push:
    branches:
      - main


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: GitHub Container Registry Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set Image Version
        id: set-version
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "VERSION=latest" >> $GITHUB_ENV
          else
            # Use the supplied version
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          fi

      - name: Docker Build and Push
        run: |
          # $VERSION is loaded from the previous step
          make docker-build docker-push IMG=ghcr.io/choreo-idp/controller:${VERSION}
